### PR TITLE
Discovery: use service UUID instead of device name

### PR DESCRIPTION
**Pull request by danielkza**
My desk was not discovered due to having a non-standard name (which I changed through the Linak app ages ago). Change discovery to use one of the advertised service UUIDs instead.

### CODE REVIEW

**Comment by newAM** [comment]
Thanks for the pull-request!

I probably will not have time to check this today, I will get to it this weekend at the latest.

**Comment by newAM** [comment]
I pushed some changes directly to your branch:

* Fixed formatting
* Fixed unit tests
* Updated minimum bleak version to 0.12 because find_device_by_filter did not exist before then
* Reduce timeout to default 30s -> 10s

Let me know what you think about the changes, if it looks good to you then I will merge this!

**Review by newAM — APPROVED** [review]

**Comment by danielkza** [comment]
Thank you for updating the tests for me, i couldn't do it until I was allowed CI runs.

Happy to know it looks good. Cheers: )

**Comment by newAM** [comment]
Excellent, merged!
I'll get this into a release sometime this weekend.

**Comment by newAM** [comment]
[v0.8.0](https://github.com/newAM/idasen/releases/tag/v0.8.0) is released with this fix, thanks again for the PR!

**Pull request merged**
